export const CLOSE_POPUP_MESSAGE = "CLOSE_POPUP_MESSAGE";

export const SEND_MAIL_EROOR = "SEND_MAIL_EROOR";
export const SEND_MAIL_SUCCESS = "SEND_MAIL_SUCCESS";

export const SET_CLIENT_SECRET_KEY = "SET_CLIENT_SECRET_KEY";
